# 端口号
server:
  port: 8762
# 服务名称，即serviceId
spring:
  profiles: peer1
  application:
    name: service-hi
# 服务注册与发现相关配置
eureka:
  instance:
      hostname: localhost
  client:
    # 服务注册地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/

---
# 端口号
server:
  port: 8763
# 服务名称，即serviceId
spring:
  profiles: peer2
  application:
    name: service-hi
# 服务注册与发现相关配置
eureka:
  instance:
      hostname: localhost
  client:
    # 服务注册地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/

---
# 端口号
server:
  port: 8764
# 服务名称，即serviceId
spring:
  profiles: peer3
  application:
    name: service-hi
# 服务注册与发现相关配置
eureka:
  instance:
      hostname: localhost
  client:
    # 服务注册地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/